[project]
name = "kubespary-offline-file-image-list"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible==9.13.0",
    "cryptography==45.0.2",
    "jmespath==1.0.1",
    "netaddr==1.3.0"
]
